application: henrypeteet
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: henrypeteet.app




libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- remote_api: on